### ISSUE TITLE
Slow performance when parsing file with no EJS code in the file.

### ISSUE THREAD

**Issue by andersjanmyr** [eta-dev/eta#227] opened 2023-05-02 13:22 UTC
When parsing a file with no EJS in, performance degrades substantially. The performance improves the closer to the end of the file the EJS code is located. 
For a 60k file (600 lines with 100 chars) with no EJS, performance is around `1400ms`. 
When I add `<%= it %>` at the end of the file (line 600), performance is`1ms`
When I add `<%= it %>` at the middle of the file (line 300), performance is`360ms`

**To Reproduce**

1. Create a large file with no EJS. (My test file is a 60k text file with 600 lines with 100 chars each.)
2. `Eta.render(body, { dummy: "yes" });`
3. Estimated time ~1400ms
4. Add `<%= it %>` at end of file.
5. Estimated time 1ms.

**Package & Environment Details**
 - OSX 12.6.2
 - Node v18.15.0

**Test case**
```
import assert from "assert";
import * as Eta from "eta";
import fs from "fs";

const body = fs.readFileSync("./dummy.txt", "utf8");
describe("metrics", function () {
  it("eta", function () {
    const start = Date.now();
    const text = Eta.render(body, { dummy: "yes" });
    const end = Date.now();
    console.log("eta " + (end - start));
    assert(text);
  });
});

```

**Comment by nebrelbug** [comment] 2023-05-07 00:20
@andersjanmyr wow, this is fascinating. Tbh, I have no idea what the cause of this bug is.

**Comment by nebrelbug** [comment] 2023-05-07 00:30
It seems that `str.slice(0, str.length)`, which is called when there are no tags in the template, may just be significantly slower than RegExp capture. I'll look into this further.

**Comment by andersjanmyr** [comment] 2023-05-07 17:45
My hack to fix the performance is to append an `<%= "" %>` to the input.

**Comment by nebrelbug** [comment] 2023-05-13 01:58
@andersjanmyr thanks for the tip. I'll see if I can fix this in Eta v3.

**Comment by joshcancode** [comment] 2023-05-13 14:13
It seems the RegExp that checks for opening and closing tags is what is causing the slow times. The RegExp consistently takes 1000ms+ to run though a 600 line file with no tags.

I added a check in the parse function to see if the file is missing any opening or closing tags, which cut down execution time to just 2ms for me.

Right above the "parseOpenReg" and "parseCloseReg" declarations, add this if check:

```ts
if (!str.includes(config.tags[0]) || !str.includes(config.tags[1])) {
  pushString(str);
  return buffer;
}
```

**Comment by nebrelbug** [comment] 2023-05-13 20:58
@joshcancode you're right, it seems it was the RegExp. I just tried a change to the RegExp itself, and it seems to resolve the problem (should work if there's a tag in the middle of the file too.)

I pushed my code to https://github.com/eta-dev/eta/tree/fix-issue-227. Do you have any feedback?

**Comment by andersjanmyr** [comment] 2023-05-14 05:32
I can confirm that the fix works. I tried to add a test case for it but, somehow the timeout (10 ms) doesn't seem to have any effect, so it doesn't actually fail. :( [jest.test docs](https://jestjs.io/docs/27.x/api#testname-fn-timeout)
```
// test/parse.spec.ts
  const largeChunkWithNoTags = "A".repeat(64 * 1024);
  test("parses large chunk with no tags with good performance", () => {
    parse(largeChunkWithNoTags, config);
  }, 10);
```

**Comment by joshcancode** [comment] 2023-05-14 15:08
> I pushed my code to https://github.com/eta-dev/eta/tree/fix-issue-227. Do you have any feedback?

Looks good to me! Consistently fast processing times, only a couple of ms now.

> I can confirm that the fix works. I tried to add a test case for it but, somehow the timeout (10 ms) doesn't seem to have any effect, so it doesn't actually fail. :( [jest.test docs](https://jestjs.io/docs/27.x/api#testname-fn-timeout)

I'm not too familiar with this library unfortunately :( I'm not sure what could be causing that.

**Comment by nebrelbug** [comment] 2023-05-17 02:28
@andersjanmyr @joshcancode just merged the fix and released in https://github.com/eta-dev/eta/releases/tag/v2.2.0!

If you come up with a way to test this, feel free to submit a PR.

Thanks for your help & feedback!

**Closed by nebrelbug** 2023-05-17 02:28 UTC
