### ISSUE TITLE
{"message":"layout is not defined"} keep throwing while using layouts

### ISSUE THREAD

**Issue by niraj-khatiwada** [eta-dev/eta#92] opened 2021-02-16 20:27 UTC
Layout defined in Login.eta
![image](https://user-images.githubusercontent.com/51436631/108117697-590fad80-70c5-11eb-8bb6-dbc8cba7bc50.png)

Folder Structure for views 
![image](https://user-images.githubusercontent.com/51436631/108117743-6f1d6e00-70c5-11eb-9eb6-a43147f389ad.png)

Layout main.eta
![image](https://user-images.githubusercontent.com/51436631/108117796-852b2e80-70c5-11eb-8b90-6d7207299f0f.png)

eta version:
![image](https://user-images.githubusercontent.com/51436631/108117851-9a07c200-70c5-11eb-99e5-c96f402a4519.png)

**Comment by niraj-khatiwada** [comment] 2021-02-16 20:28
Title Edited.

**Comment by shadowtime2000** [comment] 2021-02-16 20:51
@niraj-khatiwada Can you share a reproduction repo?

**Comment by niraj-khatiwada** [comment] 2021-02-17 08:39
@shadowtime2000  Turns out there is some issue with layout for new version of eta(i.e: 1.22 that I am using). I rolled back to v: 1.12.1 its working fine.

**Comment by shadowtime2000** [comment] 2021-02-17 08:45
@niraj-khatiwada Interesting, can you provide am minimal reproduction repo then?

**Comment by niraj-khatiwada** [comment] 2021-02-17 08:48
@shadowtime2000 , Yes sorry I forgot to include that. 

https://github.com/niraj-khatiwada/eta-layout-bug

I practiced eta with this one so I think you can have a look and figure out. 
Thanks for creating eta its awesome.

**Comment by shadowtime2000** [comment] 2021-02-17 08:50
@niraj-khatiwada Do you think you could make a **minimal** reproduction repo because that seems to be your entire app and it would probably take me a lot of time to look through it.

btw @nebrelbug created it, I just maintain it 😄

**Comment by niraj-khatiwada** [comment] 2021-02-17 09:01
@shadowtime2000 You can have a look now. Let me know if that is okay or not. 

You all guys are awesome.

**Comment by shadowtime2000** [comment] 2021-02-17 09:06
@niraj-khatiwada It's a lot easier to navigate now 😃 - but I can't seem to reproduce the error. I started it with `npm start` and i have gone to the shop `/` and the products `/products` and no errors are appearing in the console.

**Comment by niraj-khatiwada** [comment] 2021-02-17 09:11
@shadowtime2000  Because that has version 1.12.1 now. Can you upgrade that to eta@1.22 and try?

**Comment by shadowtime2000** [comment] 2021-02-17 09:13
@niraj-khatiwada Sorry, but what do you mean by `1.2`? The latest version is `1.12.1`

**Comment by niraj-khatiwada** [comment] 2021-02-17 09:19
@shadowtime2000  Thats weird  when I did "npm install eta" yesterday it installed 1.2.2?

**Comment by shadowtime2000** [comment] 2021-02-17 09:20
@niraj-khatiwada That is kind of strange. 1.2.2 is an extremely old version which doesn't have many features and isn't as fast. Probably a bug with NPM. Anyways, I am going to close this then.

**Closed by shadowtime2000** 2021-02-17 09:20 UTC

**Comment by niraj-khatiwada** [comment] 2021-02-17 09:24
@shadowtime2000 yes I think that's it. Heck NPM wasted a lot of time. Anyway thanks for all the help.
